---
- hosts: masters
  sudo: yes
  roles:
    - device-mapper

- hosts: minions
  sudo: yes
  roles:
    - device-mapper

- hosts: all
  sudo: yes
  roles:
    - common
    - kubernetes

- hosts: etcd
  sudo: yes
  roles:
    - etcd

- hosts: masters
  sudo: yes
  roles:
    - master

- hosts: minions
  sudo: yes
  roles:
    - docker-registry
    - minion

- hosts: masters
  sudo: yes
  roles:
    - flannel-master

- hosts: minions
  sudo: yes
  roles:
    - flannel-minion
