---
- hosts: all
  become: true
  gather_facts: false

  tasks:
  - name: "Wait for port 3333 to be ready"
    local_action: wait_for port=3333 host="{{ inventory_hostname }}" state=started connect_timeout=2 timeout=600

- hosts: all
  sudo: yes
  roles:
    - common
    - kubernetes

- hosts: etcd
  sudo: yes
  roles:
    - etcd

- hosts: masters
  sudo: yes
  roles:
    - master

- hosts: minions
  sudo: yes
  roles:
#    - docker-registry
    - minion

- hosts: masters
  sudo: yes
  roles:
    - flannel-master

- hosts: minions
  sudo: yes
  roles:
    - flannel-minion
