---
- hosts: cluster
  become: yes
  gather_facts: false

  tasks:
  - name: "Wait for port 3333 to be ready"
    local_action: wait_for port=3333 host="{{ inventory_hostname }}" state=started connect_timeout=2 timeout=600

- hosts: cluster
  become: yes
  roles:
    - common
    - kubernetes

- hosts: etcd
  become: yes
  roles:
    - etcd

- hosts: masters
  become: yes
  roles:
    - master

- hosts: minions
  become: yes
  roles:
#    - docker-registry
    - minion

- hosts: masters
  become: yes
  roles:
    - flannel-master

- hosts: minions
  become: yes
  roles:
    - flannel-minion
