---
- name: Install kubernetes
  yum: name=kubernetes state=latest

- name: Docker config
  template: src=docker.j2 dest=/etc/sysconfig/docker

- name: docker-storage-setup
  template: src=docker-storage-setup.j2 dest=/etc/sysconfig/docker-storage-setup

